# Generated by Django 3.2 on 2021-04-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profissional')),
            ],
        ),
    ]
